"""Accent-specific dictionary pronunciations.

The lexicon is generated by scripts/build_lexicon.py and lives in the web app's
static folder so the browser and the API read the same file.
"""
import json
import re
from functools import lru_cache
from pathlib import Path

LEXICON_PATH = Path(__file__).resolve().parent.parent / "web" / "public" / "lexicon" / "lexicon.json"
DEFAULT_ACCENT = "ga"


class UnknownWord(KeyError):
    """A word that is not in the accent lexicon."""


@lru_cache(maxsize=1)
def load_lexicon() -> dict:
    return json.loads(LEXICON_PATH.read_text(encoding="utf-8"))


def accents() -> dict:
    return load_lexicon()["accents"]


def normalize_text(text: str) -> list[str]:
    """Lowercase and split into dictionary words, dropping digits and punctuation."""
    return re.sub(r"[^a-z' ]+", " ", text.lower()).split()


def word_phonemes(word: str, accent: str = DEFAULT_ACCENT) -> list[str]:
    """Phonemes for one word. Australian falls back to the British entry it is derived from."""
    entry = load_lexicon()["words"].get(word)
    if entry is None:
        raise UnknownWord(word)
    if accent not in accents():
        raise ValueError(f"Unknown accent: {accent}")
    return (entry.get(accent) or entry["rp" if accent == "au" else "ga"]).split()


def text_phonemes(text: str, accent: str = DEFAULT_ACCENT) -> list[str]:
    """Phonemes for a word or phrase; raises UnknownWord naming the first word not in the lexicon."""
    phonemes = []
    for word in normalize_text(text):
        phonemes.extend(word_phonemes(word, accent))
    return phonemes
